TW_LOADINGSYSTEM.Enums = {
  LOADING_STATUS = {}
}

TW_LOADINGSYSTEM.Enums.LOADING_STATUS.NONE = 0
TW_LOADINGSYSTEM.Enums.LOADING_STATUS.WORKSHOP_CLEARED = 10
TW_LOADINGSYSTEM.Enums.LOADING_STATUS.DOWNLOADING = 15
TW_LOADINGSYSTEM.Enums.LOADING_STATUS.DOWNLOADED = 20
TW_LOADINGSYSTEM.Enums.LOADING_STATUS.MOUNTED = 30
